In [1]:
#1.

arr =[1,2,3,4,5,6,7,8,9,10]

In [5]:
for i in arr:
    
    if(i>6):
        print(i//2)
    else:
        print(i)

1
2
3
4
5
6
3
4
4
5


In [6]:
k = range(1,100000000000000000000000000000000000000000000000000000000000000000)

In [7]:
k[17]

18

In [18]:
def func(y):
    return lambda p: y + p


In [21]:
x = func(10)

In [25]:
x(11)

21

In [34]:
def fun (p) :
    return [i for i in range(20) if i %2==0]

print(fun(1));

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [37]:
arr = []
def fun20 (p):
    for i in range(20):
        if i%2 == 0:
            arr.append(i)



In [38]:
fun(10)

In [39]:
print(arr)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [40]:
import numpy as np

In [45]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [43]:
arr = [1,2,3,4,5,6]
arr

[1, 2, 3, 4, 5, 6]

In [51]:
np.array([1,2,3,4,5],dtype=np.int64)

array([1, 2, 3, 4, 5])

In [57]:
p = np.array([[1,2],[3,4]])
p

array([[1, 2],
       [3, 4]])

In [56]:
p[0,1]

2

In [62]:
g = np.zeros((5,2))

In [65]:
g[0,1] = 3

In [66]:
g

array([[0., 3.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
f = np.ones((5,2))

In [68]:
f

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [69]:
h = np.random.rand(2,3)

In [70]:
h

array([[0.05187335, 0.88198007, 0.78603692],
       [0.08474242, 0.6742855 , 0.17029938]])

In [73]:
np.full((3,5),"t")

array([['t', 't', 't', 't', 't'],
       ['t', 't', 't', 't', 't'],
       ['t', 't', 't', 't', 't']], dtype='<U1')